name: CheckLinks
on:
#  push:
#    branches:
#      - main
  pull_request:
    branches:
      - main

jobs:
  checklinks:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Ruby
        uses: ruby/setup-ruby@v1
      - name: Setup Rubygems, Bundler, jekyll
        run: |
          gem update --system --no-document
          gem update bundler --no-document
          gem install jekyll bundler
          bundle install
      - name: Build jekyll website
        run: bundle exec jekyll build
      - name: Check for broken links
        run: |
          bundle exec rake test &> links.log
        continue-on-error: true
      - name: Archive log links
        uses: actions/upload-artifact@v1
        with:
          name: links-check.log
          path: links.log